# Generated by Django 6.0 on 2026-08-13 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='formresponse',
            name='document_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formresponse',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='respondent_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
