# Generated by Django 6.0 on 2026-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_options_alter_formresponse_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldchoice',
            constraint=models.UniqueConstraint(fields=('field', 'order'), name='unique_choice_order_per_field'),
        ),
        migrations.AddConstraint(
            model_name='fieldchoice',
            constraint=models.UniqueConstraint(fields=('field', 'text'), name='unique_choice_text_per_field'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.UniqueConstraint(fields=('response', 'field'), name='unique_answer_per_response_field'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_field_order_per_form'),
        ),
    ]
